setw -g mouse on
set -g prefix M-a
set -g default-terminal "screen-256color"
set -g default-terminal "alacritty"

# Фоновый цвет и цвет текста панели
set -g status-style bg=default,fg=white

# Левая часть (имя сессии)
set -g status-left "#[fg=orange,bold]#S "

# Оформление вкладок (окон)
setw -g window-status-format " #I:#W "
setw -g window-status-current-format "#[bg=orange,fg=black,bold] #I:#W "

# Правая часть (дата и время)
set -g status-right "#[fg=white]%H:%M #[fg=gray]%d-%b-%y"

# Частота обновления (в секундах)
set -g status-interval 60
